version: "3.9"

services:
  api:
    image: "${API_IMAGE}"
    build: .
    volumes:
      - ".:/usr/src/app"
      - "/usr/src/api/node_modules"
    ports:
      - "${API_PORT}:${API_PORT}"
    env_file:
      - ".env"
    depends_on:
      - "broker"
      - "mongo"

  broker:
    image: nats-streaming:0.21.2-alpine3.13

  mongo:
    image: mongo:3.6.23-xenial
    volumes:
      - "/data/db"
